print("Hello world!");
print("Python has three numeric types: int, float, and complex");
myValue = 1;
print(myValue);
print(type(myValue));
print(str(myValue) + " is of the data type " + str(type(myValue)));
myValue=5j;
print(myValue);
print(type(myValue));
print(str(myValue) + " is of the data type " + str(type(myValue)));
myValue=True;
print(myValue);
print(type(myValue));
print(str(myValue) + " is of the data type " + str(type(myValue)));
myValue=False;
print(myValue);
print(type(myValue));
print(str(myValue) + " is of the data type " + str(type(myValue)));
myString = "This is a string."
print(myString);
print(type(myString));
print(myString + " is of the data type " + str(type(myString)));
firstString = "water";
secondString = "fall";
thirdString = firstString + secondString;
print(thirdString);
name = input("What is your name? ");
print(name);